[[dnas]]
id = "game-dna"
file = "./dist/connect-4.dna.json"
hash = "QmDontCheck"




[[agents]]
id = "test_agent1"
name = "HoloTester1"
public_address = "HcScjcgKqXC5pmfvka9DmtEJwVr548yd86UPtJGGoue9ynuikuRTN7oE5zcjgbi"
keystore_file = "./agent1.keystore"

[[agents]]
id = "test_agent2"
name = "HoloTester2"
public_address = "HcScidPSdAT43q9qirJwt5rHJYjjsvougV3jgSBwdJujszw3bBu5Mktr74Rgnea"
keystore_file = "./agent2.keystore"




[[instances]]
id = "instance1"
dna = "game-dna"
agent = "test_agent1"
[instances.storage]
type = "memory"
path = "tmp-storage"

[[instances]]
id = "instance2"
dna = "game-dna"
agent = "test_agent2"
[instances.storage]
type = "memory"
path = "tmp-storage"


[[interfaces]]
id = "websocket_interface"
admin = true
[interfaces.driver]
type = "websocket"
port = 3401
[[interfaces.instances]]
id = "instance1"

[[interfaces]]
id = "websocket_interface_2"
admin = true
[interfaces.driver]
type = "websocket"
port = 3402
[[interfaces.instances]]
id = "instance2"

# [[interfaces]]
# id = "http-interface1"
# [interfaces.driver]
# type = "http"
# port = 3001
# [[interfaces.instances]]
# id = "instance1"

# [[interfaces]]
# id = "http-interface2"
# [interfaces.driver]
# type = "http"
# port = 3002
# [[interfaces.instances]]
# id = "instance2"


# -----------  UI  -----------

[[ui_bundles]]
id = "main1"
root_dir = "./ui"
hash = "Qm000"

[[ui_interfaces]]
id = "ui-interface-1"
bundle = "main1"
port = 3001
dna_interface = "websocket_interface"


[[ui_bundles]]
id = "main2"
root_dir = "./ui"
hash = "Qm001"

[[ui_interfaces]]
id = "ui-interface-2"
bundle = "main2"
port = 3002
dna_interface = "websocket_interface_2"
